# Generated by Django 4.1.4 on 2023-01-04 09:14

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_verificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default=1, upload_to=user.models.get_image_path),
            preserve_default=False,
        ),
    ]
